name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4
  path_provider: ^2.0.2
  firebase_auth: ^4.15.0
  material_design_icons_flutter: 7.0.7296
  flutter_material_design_icons: ^1.1.7296
  flutter_slidable: ^3.0.1
  http: ^0.13.4
  intl: ^0.18.1
  firebase_core: ^2.24.0
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/images/fotoPerfil.jpg
    - assets/images/fotoRepuestos.jpg
    - assets/images/bujia.jpg
    - assets/images/logo.jpg

